// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQviGuB5Sy-a6B6B9Jj53SsqKcc8pUdbw',
    appId: '1:340446130275:web:40423233eef717b0e38856',
    messagingSenderId: '340446130275',
    projectId: 'abdullahtasdev',
    authDomain: 'abdullahtasdev.firebaseapp.com',
    storageBucket: 'abdullahtasdev.appspot.com',
    measurementId: 'G-BNHDQEX5L2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI9X43ZijPfY-qjp9xmMSlS9SzUs5_OH8',
    appId: '1:340446130275:android:d68ad86a2367ccb7e38856',
    messagingSenderId: '340446130275',
    projectId: 'abdullahtasdev',
    storageBucket: 'abdullahtasdev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUIdMWNj1hUpBOH4Jlgz049vDyA2Zb_eU',
    appId: '1:340446130275:ios:7bff8fd4db85de2ee38856',
    messagingSenderId: '340446130275',
    projectId: 'abdullahtasdev',
    storageBucket: 'abdullahtasdev.appspot.com',
    iosBundleId: 'com.example.flutterAbdullahtasdevBlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-9-otMn7aCL4mnI68XmMv79d0baAMJyE',
    appId: '1:937939716634:ios:0cc20b2ca9b70d2a0a1fa3',
    messagingSenderId: '937939716634',
    projectId: 'myblogapp-748bd',
    storageBucket: 'myblogapp-748bd.appspot.com',
    iosBundleId: 'com.example.flutterAbdullahtasdevBlog',
  );
}