// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgZpAzMgTSz2bW2X-02Njrz0zjkPB7hvI',
    appId: '1:937939716634:web:496b0e1baab976290a1fa3',
    messagingSenderId: '937939716634',
    projectId: 'myblogapp-748bd',
    authDomain: 'myblogapp-748bd.firebaseapp.com',
    storageBucket: 'myblogapp-748bd.appspot.com',
    measurementId: 'G-WTKF4X8JTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm2nKEu7uWf19OH1YSJsKs3goSQx0PGw0',
    appId: '1:937939716634:android:a817663cae8663f70a1fa3',
    messagingSenderId: '937939716634',
    projectId: 'myblogapp-748bd',
    storageBucket: 'myblogapp-748bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-9-otMn7aCL4mnI68XmMv79d0baAMJyE',
    appId: '1:937939716634:ios:0cc20b2ca9b70d2a0a1fa3',
    messagingSenderId: '937939716634',
    projectId: 'myblogapp-748bd',
    storageBucket: 'myblogapp-748bd.appspot.com',
    iosBundleId: 'com.example.flutterAbdullahtasdevBlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-9-otMn7aCL4mnI68XmMv79d0baAMJyE',
    appId: '1:937939716634:ios:0cc20b2ca9b70d2a0a1fa3',
    messagingSenderId: '937939716634',
    projectId: 'myblogapp-748bd',
    storageBucket: 'myblogapp-748bd.appspot.com',
    iosBundleId: 'com.example.flutterAbdullahtasdevBlog',
  );
}
